services:
    - type: web
      name: sf-api
      env: node
      plan: free
      buildCommand: npm install && npm run build
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
